build.gradle
src/main/java/site/hesil/latteve_spring/global/amazon/config/S3Config.java
src/main/java/site/hesil/latteve_spring/global/amazon/service/S3Service.java
src/main/java/site/hesil/latteve_spring/global/error/errorcode/ErrorCode.java
src/main/java/site/hesil/latteve_spring/global/error/exception/CustomBaseException.java
src/main/java/site/hesil/latteve_spring/global/error/exception/S3UploadException.java

Feat S3Upload & RedisTemplate

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/domain/Project.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/ProjectDetailResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/ProjectRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/custom/ProjectRepositoryCustom.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/custom/ProjectRepositoryImpl.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

Feat: 프로젝트 상세 정보 조회 api 완성

---

src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/ProjectDetailResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/custom/ProjectRepositoryImpl.java

- 응답 json에 리더의 github 주소, 멤버들의 github 주소 추가

Change: 프로젝트 상세 페이지 응답 json 수정

---

src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/ProjectDetailResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/custom/ProjectRepositoryImpl.java

- 리더와 멤버의 ongoingProjectCount, completedProjectCount 추가

Change: 프로젝트 상세 api 쿼리 수정

---

src/main/java/site/hesil/latteve_spring/domains/alarm/domain/Alarm.java
src/main/java/site/hesil/latteve_spring/domains/alarm/repository/AlarmRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/domain/projectMember/ProjectMember.java
src/main/java/site/hesil/latteve_spring/domains/project/domain/projectMember/ProjectMemberId.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/request/ProjectApplyRequest.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/custom/ProjectRepositoryImpl.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

- 프로젝트 지원 기능 완성
- 사용자가 프로젝트에 지원하면 project_member, alarm 테이블에 데이터 삽입
- 프로젝트에 참여하는 멤버가 없으면 에러 뜨는 버그 해결

프로젝트 지원 기능 완성 및 프로젝트 상세 정보 쿼리 수정

---

src/main/java/site/hesil/latteve_spring/global/security/jwt/Token.java
src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java
src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenService.java

소셜 로그인 기능 구현
(수정) memberId를 토큰 및 redis에 저장

Change: add memberId to token

---

build.gradle
src/main/java/site/hesil/latteve_spring/LatteveSpringApplication.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/config/MQConfig.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/exchange/DirectExchangeConfig.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/health/HealthCheck.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/publisher/MQSender.java
src/main/java/site/hesil/latteve_spring/global/security/CustomOAuth2UserService.java
src/main/resources/application.yml

feat/RabbitMQ_Exchange, Queue, routingKey, sender

---

src/main/java/site/hesil/latteve_spring/domains/member/dto/response/ResponseMember.java
src/main/java/site/hesil/latteve_spring/domains/member/service/MemberService.java

사용자 정보 조회에서 직무 정보 넣는 부분 없음
사용자 직무 조회 추가

Fix:  사용자 정보 조회에서 직무 추가

---

src/http/request.http
src/main/java/site/hesil/latteve_spring/domains/memberStack/dto/response/MemberStackResponse.java
src/main/java/site/hesil/latteve_spring/domains/memberStack/repository/MemberStackRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/domain/Project.java
src/main/java/site/hesil/latteve_spring/domains/project/domain/projectMember/ProjectMember.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/request/ProjectStartRequest.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/request/UpdateAcceptStatusRequest.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/ProjectMemberResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/response/ApplicationResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectMember/ProjectMemberRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/publisher/MQSender.java

ífeat/프로젝트 시작 & 프ë지원자 승인/거절

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/domain/Project.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/PopularProjectResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/ProjectCardResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/ProjectRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectLike/ProjectLikeRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/resources/application.yml

프로젝트 신규순 조회 api
프로젝트 최근 종료된순조회 api

Feat: 홈페이지- 신규순, 최근 종료된 순 프로젝트 조회 api

---

src/http/request.http

update/프로젝트 시작&멤버 승인,거절 api 테스트 추가

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchService.java
src/main/java/site/hesil/latteve_spring/global/security/annotation/AuthMemberId.java

Change: 프로젝트 조회에 사용자 '좋아요' 여부 추가

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectLike/ProjectLikeRepository.java
src/main/java/site/hesil/latteve_spring/domains/search/controller/SearchController.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchIndexingService.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchService.java
src/main/java/site/hesil/latteve_spring/global/security/ArgumentResolver/AuthMemberResolver.java
src/main/java/site/hesil/latteve_spring/global/security/ArgumentResolver/LoginFilterMemberIdResolver.java
src/main/java/site/hesil/latteve_spring/global/security/annotation/AuthMemberId.java
src/main/java/site/hesil/latteve_spring/global/security/annotation/LoginFilterMemberId.java

AuthMemberId 어노테이션에서 required=false 안됨
로그인 하지 않아 memberId가 안들어온경우 null로 처리하도록 수정

Change: 프로젝트 조회할 때 로그인시  좋아요 여부 조회

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/global/web/config/WebConfig.java

refactor/ProjectPost시, ProjectId 를반환

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/PopularProjectResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectLike/ProjectLikeRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectMember/ProjectMemberRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/recruitment/RecruitmentRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/domains/search/controller/SearchController.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchIndexingService.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchService.java

검색창에 keyword를 넣어야 검색 결과가 나오고 전체 프로젝트나 라떼버 볼 수 없었음
페이지 로드하면 전체 라떼버/ 프로젝트 반환됨

Change: 검색 페이지에서 페이지 로드할때 전체 카드 뜨도록 수정

---

src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/PopularProjectResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/domains/search/controller/SearchController.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchIndexingService.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchService.java

Fix: 인기 프로젝트 duration 추가

---

build.gradle
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/global/swagger/SwaggerConfig.java
src/main/resources/application.yml

http://localhost:8080/swagger-ui/index.html  접속
swagger-ui 적용

Feat: swagger-ui 적용

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/global/security/SecurityConfig.java
src/main/java/site/hesil/latteve_spring/global/swagger/SwaggerConfig.java

change: swagger 에서 쿠키 기반 인증 설정으로 변경

---

src/main/java/site/hesil/latteve_spring/domains/project/repository/recruitment/RecruitmentRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

Fix: 지원한 사람 카운트에 승인된 사람만 들어가게 변경, 직무 조회할 때 리더는 안나오도록 변경

---

src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

Fix: 프로젝트 카드, 인기 프로젝트 조회시 지원자수 승인된 멤버 수로 변경

---

src/main/java/site/hesil/latteve_spring/domains/member/repository/MemberRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectMember/ProjectMemberRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/enumerate/MQExchange.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/enumerate/MQRouting.java
src/main/java/site/hesil/latteve_spring/global/security/CustomOAuth2UserService.java
src/main/resources/application.yml

update/유저 중복체크 로직 수정

---

src/http/request.http
src/main/java/site/hesil/latteve_spring/domains/member/controller/MemberController.java
src/main/java/site/hesil/latteve_spring/domains/member/domain/Member.java
src/main/java/site/hesil/latteve_spring/domains/member/dto/request/UpdateMemberReq.java
src/main/java/site/hesil/latteve_spring/domains/member/dto/response/MemberResponse.java
src/main/java/site/hesil/latteve_spring/domains/member/service/MemberService.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

회원 닉네임, 깃허브 주소, 프로필 이미지 url, 직업, 기술스택, 자기소개  업데이트

Feat: 회원 정보 수정 api

---

src/main/java/site/hesil/latteve_spring/domains/memberStack/repository/MemberStackRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/PopularProjectResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/ProjectDetailResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/projectDetail/GetProjectDetailResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/projectDetail/ProjectDetail.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/projectDetail/ProjectDetailLeader.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/projectDetail/ProjectDetailLeaderWithoutTechStacks.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/projectDetail/ProjectDetailMember.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/projectDetail/ProjectDetailRecruitment.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/projectDetail/ProjectDetailTechStack.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/ProjectRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/custom/ProjectRepositoryCustom.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/custom/ProjectRepositoryImpl.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectMember/ProjectMemberRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/global/rabbitMQ/publisher/MQSender.java
src/main/java/site/hesil/latteve_spring/global/security/ArgumentResolver/AuthMemberResolver.java
src/main/resources/application.yml

Change/ì/관리탭 쿼리 최적화

---

src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/PopularProjectResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/ProjectRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/custom/ProjectRepositoryCustom.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/custom/ProjectRepositoryImpl.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchIndexingService.java

Refactor: 홈페이지 - 인기 프로젝트 성능 개선

---

src/main/java/site/hesil/latteve_spring/global/web/config/WebConfig.java

webconfig 변경

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java
src/main/java/site/hesil/latteve_spring/domains/retrospective/domain/Retrospective.java

Feat: 회고 수정 api

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

- 프로젝트 지원 여부를 확인하는 isApplication 메서드 생성

Feat: 지원 여부 확인 api

---

src/main/resources/application.yml

Fix: authorized-redirect-uris 추가

---

src/main/java/site/hesil/latteve_spring/domains/alarm/dto/ProjectApplicationAlarm.java
src/main/java/site/hesil/latteve_spring/domains/alarm/dto/ProjectApprovalResultAlarm.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

refactor: type 추가, memberId 추가

---

src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

refactor: rabbitMQ 와 라우팅키 매칭

---

src/main/java/site/hesil/latteve_spring/domains/alarm/dto/ProjectApplicationAlarm.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

refactor: 사용자 이미지추가

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java

- 로그인한 멤버와 파라미터로 넘겨받은 멤버가 같은지 체크하는 컨트롤러 메서드 추가

Feat: 프로젝트 참여 여부 확인 api 추가

---

src/main/java/site/hesil/latteve_spring/domains/alarm/domain/Alarm.java
src/main/java/site/hesil/latteve_spring/domains/alarm/repository/AlarmRepository.java
src/main/java/site/hesil/latteve_spring/domains/memberStack/repository/MemberStackRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectMember/ProjectMemberRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

refactor: 프로젝트업데이트/시작시 alarm테이블저장

---

src/main/java/site/hesil/latteve_spring/domains/alarm/repository/AlarmRepository.java
src/main/java/site/hesil/latteve_spring/domains/project/service/ProjectService.java

refactor: 승인 거절 지원 알람 반영

---

src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java

배포 환경에서 토큰 담긴 쿠키가  저장 안 되는 문제 수정

Fix: addJwtCookieToResponse

---

src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java

Fix: 로그 추가

---

src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java

Fix: 도메인 설정 추가

---

src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java

Fix: 도메인 설정 변경

---

src/main/java/site/hesil/latteve_spring/global/security/OAuth2SuccessHandler.java
src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java

Test: access token 쿼리스트링으로 넘겨 주고 프론트에서 쿠키에 저장

---

src/main/java/site/hesil/latteve_spring/domains/alarm/dto/ApplicationResultAlarm.java
src/main/java/site/hesil/latteve_spring/domains/alarm/dto/RequestAlarm.java
src/main/java/site/hesil/latteve_spring/domains/alarm/repository/AlarmRepository.java

- ApplicationResultAlarm, RequestAlarm에 alarmId 추가

Change: 알람 dto에 alarmId 추가

---

src/main/java/site/hesil/latteve_spring/domains/member/controller/MemberController.java
src/main/java/site/hesil/latteve_spring/global/security/ArgumentResolver/AuthMemberResolver.java
src/main/java/site/hesil/latteve_spring/global/security/ArgumentResolver/LoginFilterMemberIdResolver.java
src/main/java/site/hesil/latteve_spring/global/security/OAuth2SuccessHandler.java
src/main/java/site/hesil/latteve_spring/global/security/SecurityConfig.java
src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenAuthenticationFilter.java
src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java

Change: 토큰 저장 방식 쿠키에서 로컬 스토리지로 변경

---

src/main/java/site/hesil/latteve_spring/global/security/SecurityConfig.java

Fix: security 권한 설정 변경

---

src/main/java/site/hesil/latteve_spring/global/security/SecurityConfig.java

Fix: OPTIONS 설정 순서 오류 수정

---

src/main/java/site/hesil/latteve_spring/global/config/CorsConfig.java
src/main/java/site/hesil/latteve_spring/global/security/SecurityConfig.java

Add: cors 설정 파일 추가

---

src/main/java/site/hesil/latteve_spring/domains/project/repository/project/custom/ProjectRepositoryImpl.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/projectMember/ProjectMemberRepository.java
src/main/java/site/hesil/latteve_spring/domains/search/service/SearchService.java

Fix: 지원한 멤버에 프로젝트 리더 들어가는 문제 해결

---

src/main/java/site/hesil/latteve_spring/domains/member/service/MemberService.java

fix_dataSync__mongo_insert_sync

---

src/main/java/site/hesil/latteve_spring/domains/project/dto/project/response/ProjectDetailResponse.java
src/main/java/site/hesil/latteve_spring/domains/project/repository/project/custom/ProjectRepositoryImpl.java

- 프로젝트 상세 페이지 쿼리에서 리더와 참여 멤버의 경력을 가져오도록 변경

Change: 프로젝트 상세 페이지 쿼리 수정

---

src/main/java/site/hesil/latteve_spring/domains/project/controller/ProjectController.java
src/main/java/site/hesil/latteve_spring/domains/project/dto/request/isLeader/IsLeaderRequest.java

fix:IsLeader검증API추가

---

src/main/java/site/hesil/latteve_spring/global/security/jwt/TokenProvider.java

Fix: token-expiration
